// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paluzqdyjmgkiycpziiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhbHV6cWR5am1na2l5Y3B6aWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODgzNzQsImV4cCI6MjA1MzA2NDM3NH0.08qyTX28e8Kdrt__MH7xL2CwUM7BMBlrK730EKeET1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);